export const PUBLIC_INCIDENT_PROVIDERS = Object.freeze([
  Object.freeze({
    id: 'austin-fire',
    jurisdiction: 'Austin, Texas, USA',
    agency: 'Austin Fire Department',
    label: 'Austin Fire',
    platform: 'socrata',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint:
      "https://data.austintexas.gov/resource/wpu4-x69d.json?$where=traffic_report_status='ACTIVE'&$order=published_date%20DESC&$limit=500",
    sourceUrl: 'https://data.austintexas.gov/d/wpu4-x69d',
    fields: Object.freeze({
      sourceId: 'traffic_report_id',
      type: 'issue_reported',
      title: 'issue_reported',
      description: 'address',
      lat: 'latitude',
      lon: 'longitude',
      time: 'published_date',
      status: 'traffic_report_status',
    }),
  }),

  Object.freeze({
    id: 'seattle-fire',
    jurisdiction: 'Seattle, Washington, USA',
    agency: 'Seattle Fire Department',
    label: 'Seattle Fire',
    platform: 'socrata',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint:
      'https://data.seattle.gov/resource/kzjm-xkqj.json?$order=datetime%20DESC&$limit=500',
    sourceUrl: 'https://data.seattle.gov/d/kzjm-xkqj',
    timeZone: 'America/Los_Angeles',
    fields: Object.freeze({
      sourceId: 'incident_number',
      type: 'type',
      title: 'type',
      description: 'address',
      lat: 'latitude',
      lon: 'longitude',
      time: 'datetime',
      status: null,
    }),
  }),

  Object.freeze({
    id: 'phoenix-fire',
    jurisdiction: 'Phoenix, Arizona, USA',
    agency: 'Phoenix Fire Department',
    label: 'Phoenix Fire',
    platform: 'arcgis',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint:
      'https://maps.phoenix.gov/phxfire/rest/services/Active_Incidents__Public/MapServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson',
    sourceUrl:
      'https://maps.phoenix.gov/phxfire/rest/services/Active_Incidents__Public/MapServer/0',
    fields: Object.freeze({
      sourceId: 'Incident',
      type: 'Nature',
      title: 'NatureDesc',
      description: 'GenLocInfo',
      lat: null,
      lon: null,
      time: 'Date',
      status: null,
    }),
  }),

  Object.freeze({
    id: 'houston-active-incidents',
    jurisdiction: 'Houston, Texas, USA',
    agency: 'Houston Emergency Center',
    label: 'Houston Active Incidents',
    platform: 'arcgis',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint:
      'https://mycity2.houstontx.gov/pubgis01/rest/services/HEC/HEC_Active_Incidents/MapServer/0/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson',
    sourceUrl:
      'https://mycity2.houstontx.gov/pubgis01/rest/services/HEC/HEC_Active_Incidents/MapServer/0',
    fields: Object.freeze({
      sourceId: 'UID',
      type: 'Agency',
      title: 'IncidentType',
      description: 'Address',
      lat: null,
      lon: null,
      time: 'CALL_TIME',
      status: null,
    }),
  }),

  Object.freeze({
    id: 'san-diego-fire',
    jurisdiction: 'San Diego, California, USA',
    agency: 'San Diego Fire-Rescue Department',
    label: 'San Diego Fire-Rescue',
    platform: 'arcgis',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint:
      'https://webmaps.sandiego.gov/arcgis/rest/services/SDFR/FireMap_Incidents/FeatureServer/0/query?where=IsActive%3D-1&outFields=*&returnGeometry=true&outSR=4326&f=geojson',
    sourceUrl:
      'https://webmaps.sandiego.gov/arcgis/rest/services/SDFR/FireMap_Incidents/FeatureServer/0',
    fields: Object.freeze({
      sourceId: 'MasterIncidentNumber',
      type: 'ProblemCode',
      title: 'ProblemDescription',
      description: 'Address',
      lat: null,
      lon: null,
      time: 'ResponseDate',
      status: 'PriorityDescription',
    }),
  }),

  Object.freeze({
    id: 'monroe-county-911',
    jurisdiction: 'Monroe County, New York, USA',
    agency: 'Monroe County 911',
    label: 'Monroe County 911',
    platform: 'xml',
    format: 'rss',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint: 'https://www.monroecounty.gov/incidents911.rss',
    sourceUrl: 'https://www.monroecounty.gov/safety-incidents',
  }),

  Object.freeze({
    id: 'portland-911',
    jurisdiction: 'Portland, Oregon, USA',
    agency: 'Portland 911',
    label: 'Portland 911',
    platform: 'xml',
    format: 'atom',
    cadenceMinutes: 5,
    freshnessClass: 'live',
    endpoint: 'https://www.portlandmaps.com/scripts/911incidents.cfm',
    sourceUrl: 'https://www.portlandmaps.com/',
  }),
]);
